### PR TITLE
Fix node version for TravisCI

### PR DESCRIPTION
**Pull request by rianby64**
I chose the version for CentOS and seems that works.

### CODE REVIEW

**Comment by rianby64** [comment]
I signed it!

**Comment by rianby64** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thanks, yeah that travis file is completely outdated, could you change it to mirror the versions karma supports: https://github.com/karma-runner/karma/blob/master/.travis.yml#L4-L7

**Comment by rianby64** [comment]
Thanks for the suggestion. Hope this change is that same that you expect.

**Comment by dignifiedquire** [comment]
Looks good, thank you :octocat:

**Comment by rianby64** [comment]
Thanks a lot to allow to contribute :+1:

**Pull request merged**
